markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
pygments: true
url: http://cb.platan.us
name: Código Banana
description: El blog oficial de Platanus
paginate: 8
remote_layout_url: http://platan.us/blog-assets
remote_layouts:
    - default