markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
pygments: true
url: http://cb.platan.us
name: Código Banana
description: El blog oficial de Platanus
remote_layout_url: http://192.168.10.140:3000/blog-assets
remote_layouts:
    - default
    - test
