# Site settings
title: Codigo Banana
email: contact@platan.us
description: > # this means to ignore newlines until "baseurl:"
  El blog oficial de Platanus
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cb.platan.us" # the base hostname & protocol for your site
github_username:  platanus

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
highlighter: rouge

# Fetch data settings
data_fetch_resources:
  - url: http://platan.us/team.json
    name: team
    item_name_key: slug

